# Generated by Django 5.1.4 on 2025-04-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
    ]
